name: flutter_bluetooth_print_plugin
description: A flutter connect bluetooth printer plugin.
version: 1.0.0
author: Ning<lining201702@gmail.com>
homepage: https://github.com/NingLi-iOSer/flutter_bluetooth_print_plugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.flutter_bluetooth_print_plugin
    pluginClass: FlutterBluetoothPrintPlugin